version: "3"
services:
  trabalho:
    build: .
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
      net.ipv4.ip_forward: 1
    command: /bin/bash
    volumes:
      - ./:/home/redes2
    cap_add:
      - NET_ADMIN
